<table border=0 class="maintable" width="100%" height=690 cellspacing=0 cellpadding=3>
<tr>
	<td valign=top>

	<table border=0 cellspacing=0 cellpadding=5 width=100%>
	<tr>
		<td><font class="viennacat"><?=strtoupper($LANG_SETTINGS['menu']['official']);?></font></td>
	</tr>

	<tr><td height="10"><img src="images/spacer.gif" height="10"></	td></tr>
	
	<tr>
		<td>
		<?
			include('incs/restables/reslisttab_allofficial.php.inc');
		?>
		</td>
	</tr>

	
	</table>
	</td>
</tr>
</table>
